title: LemonFan
description:Personal blog

url: https://github.com/lem0nfan
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: lem0nfan
  twitter: lemonfan10
  facebook: fan.lemon.790
  email: auroravvzx@gmail.com

google_analytics: "UA-58263416-1"
