# Site settings
title: LemonFan
email: auroravv@163.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/zetsu"
url: "http://lemonfan.me"

author:
  name     : 'LemonFan'
  email    : auroravv@163.com
  url      : https://lemonfan.me
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/lem0nfan/lem0nfan.github.io
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
